openapi: 3.0.0
info:
  title: Aria Service
  version: 0.0.0
tags:
  - name: account
  - name: auth
  - name: vendor-category
paths:
  /api/account:
    post:
      tags:
        - account
      operationId: AccountService_create
      parameters: []
      responses:
        '201':
          description: The request has succeeded and a new resource has been created as a result.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account.Account'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Account.Account'
      security:
        - BearerAuth: []
    get:
      tags:
        - account
      operationId: AccountService_list
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account.Account'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - BearerAuth: []
  /api/account/{id}:
    delete:
      tags:
        - account
      operationId: AccountService_delete
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - BearerAuth: []
    put:
      tags:
        - account
      operationId: AccountService_put
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account.Account'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - BearerAuth: []
  /api/member/exists:
    get:
      tags:
        - auth
      operationId: AuthService_exists
      parameters:
        - name: memberEmail
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/Auth.Email'
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: boolean
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/member/sign-in:
    post:
      tags:
        - auth
      operationId: AuthService_signIn
      parameters: []
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Auth.SignInInfo'
  /api/member/sign-up:
    post:
      tags:
        - auth
      operationId: AuthService_signUp
      parameters: []
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Auth.SignUpInfo'
  /api/member/verify-email/{code}:
    post:
      tags:
        - auth
      operationId: AuthService_verifyEmail
      parameters:
        - name: code
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  token:
                    type: string
                required:
                  - message
                  - token
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/vendor-category:
    post:
      tags:
        - vendor-category
      operationId: VendorCategoryService_create
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VendorCategory.VendorCategoryResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VendorCategory.CreateVendorCateogry'
      security:
        - BearerAuth: []
    get:
      tags:
        - vendor-category
      operationId: VendorCategoryService_list
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/VendorCategory.VendorCategoryResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - BearerAuth: []
  /api/vendor-category/{id}:
    delete:
      tags:
        - vendor-category
      operationId: VendorCategoryService_delete
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - BearerAuth: []
    put:
      tags:
        - vendor-category
      operationId: VendorCategoryService_put
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VendorCategory.VendorCategoryResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VendorCategory.UpdateVendorCateogry'
      security:
        - BearerAuth: []
components:
  schemas:
    Account.Account:
      type: object
      required:
        - id
        - alias
        - bank
        - accountNumber
        - accountHolder
      properties:
        id:
          type: integer
        alias:
          type: string
          description: 별명
        bank:
          type: string
          description: 은행 이름
        accountNumber:
          type: string
          description: 계좌번호
        accountHolder:
          type: string
          description: 예금주
    Auth.Email:
      type: string
      format: email
    Auth.Password:
      type: string
      minLength: 8
    Auth.SignInInfo:
      type: object
      required:
        - email
        - password
      properties:
        email:
          $ref: '#/components/schemas/Auth.Email'
        password:
          $ref: '#/components/schemas/Auth.Password'
    Auth.SignUpInfo:
      type: object
      required:
        - email
        - password
        - nickname
      properties:
        email:
          $ref: '#/components/schemas/Auth.Email'
        password:
          $ref: '#/components/schemas/Auth.Password'
        nickname:
          type: string
    Auth.User:
      type: object
      required:
        - email
        - password
        - nickname
      properties:
        email:
          $ref: '#/components/schemas/Auth.Email'
        password:
          $ref: '#/components/schemas/Auth.Password'
        nickname:
          type: string
    Building.Building:
      type: object
      required:
        - id
        - name
        - address
        - lotAddress
        - bjdongCode
        - bonbun
        - bubun
        - completedAt
        - createdAt
        - updatedAt
        - vendors
        - memo
        - feeAccount
        - feeDepositDay
      properties:
        id:
          type: integer
        name:
          type: string
        address:
          type: string
          description: 건물 도로명 주소
        lotAddress:
          type: string
          description: 건물 지번 주소
        bjdongCode:
          type: string
          maxLength: 10
          description: |-
            법정동 코드
            참조: https://www.code.go.kr/stdcode/regCodeL.do
        bonbun:
          type: string
          maxLength: 4
          description: 번
        bubun:
          type: string
          maxLength: 4
          description: 지
        completedAt:
          type: string
          format: date
          description: 준공일(계약서에 명시하지 않은 경우 사용승인일)
        createdAt:
          type: string
          format: date
        updatedAt:
          type: string
          format: date
        vendors:
          type: array
          items:
            $ref: '#/components/schemas/Vendor.Vendor'
        memo:
          type: string
          description: 빌딩에 대한 메모
        feeAccount:
          allOf:
            - $ref: '#/components/schemas/Account.Account'
          description: 관리비 계좌
        feeDepositDay:
          type: integer
          minimum: 1
          maximum: 31
          description: 관리비 입금일
    Error:
      type: object
      required:
        - message
      properties:
        errorCode:
          type: integer
          format: int32
        message:
          type: string
    Vendor.Vendor:
      type: object
      required:
        - name
        - phoneNumber
        - email
      properties:
        name:
          type: string
          minLength: 1
          description: 이름
        phoneNumber:
          type: string
          pattern: ^[0-9]{2,3}-[0-9]{3,4}-[0-9]{4}$
          description: 전화번호
        email:
          type: string
          format: email
          description: 이메일
        businessNumber:
          type: string
          pattern: ^[0-9]{10}$ | ^[0-9]{3}-[0-9]{2}-[0-9]{5}$
          description: 사업자 번호
    VendorCategory.CreateVendorCateogry:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 30
    VendorCategory.UpdateVendorCateogry:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 30
    VendorCategory.VendorCategory:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 30
    VendorCategory.VendorCategoryResponse:
      type: object
      required:
        - name
        - id
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 30
        id:
          type: integer
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
servers:
  - url: http://localhost:8080
    description: development
    variables: {}
  - url: http://ariasol.co.kr
    description: production
    variables: {}
